branch-defaults:
  master:
    environment: sherrill-brian-webdev
global:
  application_name: Test
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-2
  profile: eb-cli2
  sc: git
