const HOMEOWNER = 'HOMEOWNER',
    CAR_OWNER = 'CAR_OWNER',
    MEDICINE_TAKER = 'MEDICINE_TAKER',
    CUSTOM = 'CUSTOM';

module.exports = {
    HOMEOWNER,
    CAR_OWNER,
    MEDICINE_TAKER,
    CUSTOM,
    EVENT_GENERATOR_TYPES: [HOMEOWNER, CAR_OWNER, MEDICINE_TAKER, CUSTOM]
};

